### ISSUE TITLE
Error on Import

### ISSUE THREAD

**Issue by ChadBonanno** [ReshotAI/gaussian-splatting-blender-addon#3]
Getting an error when importing PolyCam Gaussian Splatting SPLAT PLY files into Blender using your Addon.

Error line 229 
Opacity_geom_attr_node.outputs ["Value"]
KeyError-  bpy_prop_collection[key] : Key "Value" not found

**Comment by ChadBonanno** [comment]
Thank you so much!   I am so excited about this development!  You have my FULL SUPPORT !!🤟🤟🤟🤟🤟🤟BestChad-  -  -  -  -  -  -  -  -Chad BonannoDesign+Direction323-527-4119www.chadbonanno.comwww.tempestfreerunning.comOn Oct 3, 2023, at 10:14 AM, Alexandre Carlier ***@***.***> wrote:﻿
Thanks for trying the add-on! Seems it's the same issue as #2. Will try to work on this hopefully this evening.

**Comment by alexandre01** [comment]
Solved ✅
