### ISSUE TITLE
Particles are round and not the original shape

### ISSUE THREAD

**Issue by SilvioMueller** [ReshotAI/gaussian-splatting-blender-addon#32]
Blender:
![Screenshot 2024-04-05 170455_mod](https://github.com/ReshotAI/gaussian-splatting-blender-addon/assets/16036727/221d88f8-546c-4d37-9b66-afa8927791a6)
Other Viewer:
![Screenshot 2024-04-05 171026_mod](https://github.com/ReshotAI/gaussian-splatting-blender-addon/assets/16036727/022d0e4e-b14b-4ab4-a9fc-5a6219e61a63)

For me the the particles in blender are round and not the "splatted" shape they should have. In other viewers the GS file looks correct. Did someone have the same problem?

**Comment by SilvioMueller** [comment]
I just had to deactivate "as point cloud" in the 3D Gaussian Splatting menu.....

**Comment by ch1998** [comment]
Hi ， what's the vision of your blender and addon? After installing the plug-in and importing Gaussian ply, there is no option as point cloud in the menu.
![image](https://github.com/ReshotAI/gaussian-splatting-blender-addon/assets/37291486/dad50e7d-ac3e-4932-b524-c19270c8c1da)
