### ISSUE TITLE
Error on Export

### ISSUE THREAD

**Issue by Elvis33LE** [ReshotAI/gaussian-splatting-blender-addon#6]
I get this error on exporting. Wanted to adjust the rotation and posotion for later use and reexport.
Unfortunately the mesh has no position attribute.

Python: Traceback (most recent call last):
  File "C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blender-addon\__init__.py", line 1075, in execute
    xyz[i] = position_attr.data[i].vector.to_tuple()
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by legsoft** [comment]
Had the same problem. Open the _init_.py file of the plugin.

Comment Out Line 1075
`#xyz[i] = position_attr.data[i].vector.to_tuple()`

Replace Line 1058
`xyz = np.zeros((N, 3))`
With
`xyz = np.array([vert.co for vert in mesh.vertices])`
